# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: steps examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: verification of node version
      run: node --version
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - id: step-caller
        uses: "/.github/actions/hello"
        with:
          the-caller: 'Myself'
      - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
        shell: bash
